const eng = document.querySelector('.eng');
const tur = document.querySelector('.tur');
const cevir = document.querySelector('.cevir');
const ceviri = document.querySelector('.ceviri');
let card = document.querySelector('.card');

let dizi = [
    {eng : "How many times do you brush your teeth?", tur: "Dişlerini kaç kere fırçalarsın?"},
    {eng : "Can you drive a car?", tur: "Araba sürebilir misin?", seviye: "1"},
    {eng : "Where do you live?", tur: "Nerede yaşıyorsun?"},
    {eng : "What about you?", tur: "Ya senden naber?"},
    {eng : "Why not!", tur: "Neden olmasın?"},    
    {eng : "What's up!", tur: "Naber", ans1 : "All is well", ans2 : "so so"},
	{eng : "What's the matter?", tur: "Sorun/problem ne?"},
    {eng : "Get well soon", tur: "geçmiş olsun"},
	{eng : "I have no money", tur: "Hiç param yok"},
	{eng : "My mistake", tur: "benim hatam"},
	{eng : "I get it!", tur: "Anladım/ anlıyorum."},
	{eng : "Do you need any help?", tur: "Yardıma ihtiyacın var mı?"},
	{eng : "Don't worry!", tur: "Endişelenme"},
	{eng : "Get relaxed", tur: "Rahatla!"},
	{eng : "You are wellcome", tur: "Bir şey değil."},
	{eng : "that's very kind of you", tur: "Çok naziksiniz"},
	{eng : "Could you do me a favour please", tur: "Bana bir iyilik yapar mısınız, lütfen"},
	{eng : "I feel weird.", tur: "Tuhaf hissediyorum"},
	{eng : "How did it happen", tur: "Nasıl oldu, nasıl gerçekleşti"},
	{eng : "How is it going?", tur: "Nasıl gidiyor (işler, hayat)"},
	{eng : "As a bomb", tur: "Bomba gibi"},
	{eng : "I'm proud of you", tur: "Seninle gurur duyuyorum"},
	{eng : "By the way", tur: "bu arada ..."},
	{eng : "You seem to be out of sorts", tur: "Keyifsiz görünüyorsun"},
	{eng : "Just let it go", tur: "Takma kafana, sal gitsin"},
	{eng : "No way", tur: "asla, oluru yok."},
	{eng : "No options", tur: "Başka seçenek yok"},
	{eng : "I see", tur: "anlıyorum"},
	{eng : "fire away", tur: "konuşmaya başla, öt"},
	{eng : "Are you kidding me!", tur: "Dalga mı geçiyorsun"},
	{eng : "What are you talking about", tur: "(... hakkında) Ne diyorsun"},
	{eng : "There is so much more", tur: ""},
	{eng : "Guess what", tur: "Tahmin et bakalım"},
	{eng : "That's indeed", tur: "aynen öyle"},
	{eng : "get out of here", tur: ""},
	{eng : "Who did that", tur: "bunu kim yaptı"},
	{eng : "You can't just walk in here like that", tur: "BUrada bu şekilde dolaşamazsın"},
	{eng : "I wanna talk to you", tur: "Seninle konuşmam gerek"},
	{eng : "I don't know where they are", tur: "Onları nerede olduğunu bilmiyorum"},
	{eng : "I will find out what it is", tur: ""},
	{eng : "Let's hang out", tur: ""},
	{eng : "get on the car", tur: "(hemen) arabaya bin"},
	{eng : "What do you think about this topic?", tur: "Bu konu hakkında ne düşünüyorsun"},
	{eng : "Nothing special", tur: ""},
	{eng : "This is where we start", tur: ""},
	{eng : "Where were you born?", tur: "Nerede doğdun?"},
	{eng : "I was born in Ankara.", tur: "Ankarada doğdum"},
	{eng : "When were you born?", tur: "Ne zaman doğdun?"},
	{eng : "I was born in nineteen seventyseven", tur: "1977'de doğdum"},
	{eng : "What color are your eyes?", tur: "Gözlerin ne renk?"},
	{eng : "They are brown", tur: "Onlar kahverengi"},
	{eng : "What is your weight?", tur: "Ağırlığın ne?"},
	{eng : "I am ninety kilos", tur: "90 kiloyum"},
	{eng : "What is your job.", tur: "Mesleğin ne?"},
	{eng : "I don't have a job.", tur: "Bir mesleğim yok"},
	{eng : "What do you want to be in the future?", tur: "Gelecekte ne yapmak istiyorsun?"},
	{eng : "I want to be a full stack developer in the future", tur: "gelecekte full stack developer olmak istiyorum"},
	{eng : "Which fruit do you eat the most?", tur: "Hangi meyveyi en çok yersin?"},
	{eng : "What is the most crowded city in Turkey?", tur: "Türkiyedeki en kalabalık şehir hangisi?"},
	{eng : "Istanbul is the most crowded city in Turkey.", tur: "İstanbul Türkiyedeki en kalabalık şehirdir."},
	{eng : "Where do you live?", tur: "Nerede yaşıyorsun?"},{eng : "I live in Ankara", tur: "Ankarada yaşıyorum"},
	{eng : "Which sports are you interested in?", tur: "Hangi sporlara ilgi duyuyorsun?"},
	{eng : "I am interested in basketball and soccer.", tur: "Basketbol ve futbola ilgi duyuyorum."},
	{eng : "How many languages can you speak?", tur: "Kaç tane dil konuşabiliyorsun?"},
	{eng : "I can speak two languages", tur: "2 yabancı dil konuşabiliyorum."},
	{eng : "Turkish and a little bit english", tur: "Türkçe ve bir parça ingilizce"},
	{eng : "Which vegetables do you eat the most?", tur: "En çok hangi sebzeyi yersin?"},
	{eng : "I eat tomato the most", tur: "En çok domates yerim"},
	{eng : "Which lesson is difficult for you?", tur: "Hangi ders senin için zor"},
	{eng : "Literature is difficult for me", tur: "Edebiyat benim için zor"},
	{eng : "When do you usually wake up?", tur: "Genellikle kaçta kalkarsın?"},
	{eng : "I usually wake up 6 a.m", tur: "Genellikle sabah 6'da kalkarım"},
	{eng : "Do you get angry easily?", tur: "Kolayca sinirlenir misin?"},
	{eng : "I get angry easily", tur: "Kolayca sinirlenirim"},
	{eng : "I am a cool person", tur: "Sakin biriyim"},
	{eng : "Can you drive a car?", tur: "Araba sürebilir misin?"},
	{eng : "How many times do you eat a day?", tur: "Bir günde kaç sefer yemek yersin?"},
	{eng : "I eat two times a day", tur: "Günde iki sefer yemek yerim"},
	{eng : "How many times do you brush your teeth?", tur: "Dişlerini kaç sefer fırçalarsın?"},
	{eng : "I brush my teeth twice a day", tur: "Dişlerimi günde iki sefer fırçalarım."},
	{eng : "What size do you wear?", tur: "Hangi bedeni giyiyorsun?"},
	{eng : "I wear medium size", tur: "Orta beden giyiyorum"},
	{eng : "Have you ever been abroad?", tur: "Hiç yurt dışında bulundun mu?"},
	{eng : "No, I have never been abroad.", tur: "Hayır daha önce hiç yurt dışında bulunmadım"},
    {eng : "Yes, I have been to Norway", tur: "Eveti Norveçte bulundum."},
    {eng : "How do you usually go to house?", tur: "Eve genellikle nasıl gidersin?"},
    {eng : "I usually go to house by bus/ by car/on foot", tur: "Eve genellikle otobus/araba/yürüyerek ile giderim"},
    {eng : "What kind of books do you read?", tur: "Ne tür kitaplar okursun?"},
    {eng : "I read history books", tur: "Tarih kitapları okurum"},
    {eng : "Which city is the most crowded city in the world?", tur: "Dünyadaki en kalabalık şehir hangisidir?"},
    {eng : "Tokio is the most crowded city", tur: "Tokyo dünyanın en kalabalık şehridir."},
    {eng : "Which one is more important, health or money?", tur: "Hangisi daha önemli, sağlık mı, para mı?"},
    {eng : "Of course health is more important", tur: "tabiki sağlık daha önemli"},
    {eng : "What do you do at the weekends?", tur: "Haftasonları ne yaparsın.?"},
    {eng : "I play outside with my friends", tur: "Dışarıda arkadaşlarımla oynarım."},
    {eng : "I have a rest in my room", tur: "Odamda dinlenirim"},
    {eng : "I go shopping with my family.", tur: "Ailemle alış verişe giderim"},
    {eng : "What will you do tonight?", tur: "Bu gece ne yapacaksın."},
    {eng : "I will meet my friends", tur: "Arkadaşlarımla buluşacağım"},
    {eng : "I am not sure", tur: "Emin değilim"},
    {eng : "Maybe, I will sleep early", tur: "Belki erken uyurum"},
    {eng : "Where did you go (to) last summer?", tur: "Geçen yaz nereye gittin"},
    {eng : "I went to home town, Karaman", tur: "memlekete Karamana gittim"},
    {eng : "What is the longest river in the world?", tur: "Dünyadaki en uzun nehir nedir?"},
    {eng : "Nile river is the longest one", tur: "Nil nehri en uzunudur"},
    {eng : "What are the two big lakes in Turkey?", tur: "Tükiyedeki iki büyük göl nedir?"},
    {eng : "They are lake Van and Lake Salt", tur: "Onlar Van Gölü ve Tuz gölüdür"},
    {eng : "What is the capital city of Turkey?", tur: "Türkiyenin başkenti nedir?"},
    {eng : "Ankara is the capital city of Turkey.", tur: "Ankara Türkiyenin başkentidir."},
    {eng : "How many geographical regions are there in Turkey?", tur: "Türkiyede kaç tane cografi bölge vardır?"},
    {eng : "There are seven regions", tur: "Yedi bölge var."},
    {eng : "What do you think about economy in your country?", tur: "Ülkendeki ekonomi hakkında ne düşünüyorsun?"},
    {eng : "Not so good, not so bad", tur: "ne çok iyi, ne çok kötü"},
    {eng : "It is getting better", tur: "İyiye gidiyor"},
    {eng : "What do you think to buy first, house or car?", tur: "Hangisini önce alırsın, ev mi, araba mı?"},{eng : "Have you ever taste a chinese food?", tur: "Daha önce hiç Çin yemeği tattın mı?"},
    {eng : "Can you prepare any meal?", tur: "Hiç yemek hazırlayabilir misin?"},{eng : "No I have never taste.", tur: "hayır, hiç tatmadım"},
    {eng : "First, I want to buy a house, but I think buying car is easier.", tur: "Önce ev almak isterim ama bence araba almak daha kolay"},
    {eng : "I can prepare pasta.", tur: "Makarna hazırlayabilirim"},
    {eng : "If you have enough money, do you want change your city?", tur: "Yeteri kadar paran olsaydı, şehrini değiştirirmiydin?"},
    {eng : "Yes I want to move to Salt Lake City in US.", tur: "Evet, US'deki Salt lake City ye taşınmak isterim"},
    {eng : "Where is the Atlantic Ocean?", tur: "Atlantic okyanusu nerede?" },
    {eng : "It is between America and Africa", tur: "America ve AFrika arasında"},
    {eng : "	Bugün evdemisin?	", tur: "	Are you at home today?	"},
{eng : "	Bugün evde değilim, ama yarın evdeyim. 	", tur: "	I am not at home but I am at home tomorrow	"},
{eng : "	Kardeşinin çok güzel gözleri var.	", tur: "	Your brother has very beatiful eyes	"},
{eng : "	Onlar sınıfta öğretmenle birlikteydiler.	", tur: "	They were with the teacher together in the class	"},
{eng : "	Ayşe’nin elbisesinin rengi kırmızıdır.	", tur: "	The color of Ayşe's dress is red.	"},
{eng : "	O Almanya’da çok zengin biridir.	", tur: "	He is very rich person in Germany	"},
{eng : "	Kaan her zaman neşeli bir çocuktur.	", tur: "	Kaan is a happy kid every time	"},
{eng : "	Ben okula giderim	", tur: "	I go to school	"},
{eng : "	Ben okula otobusle giderim	", tur: "	I go to school by bus (vbir şey vasıtasıyla by, birisi ile with)	"},
{eng : "	Annem her gün yemek yapar	", tur: "	My mother cooks in the kitchen everyday.	"},
{eng : "	Ayşe ve Sevda Cambridge üniversitesinden mezun oldu.	", tur: "	Ayşe and Sevda graduated from The Cambridge Univesity	"},
{eng : "	Ahmet’in kız kardeşi dün annesi için hastanede kaldı.	", tur: "	Ahmet's sister stayed at hospital for your mother	"},
{eng : "	Evin tadilatı için çok paraya ihtiyacımız var.	", tur: "	We need a lot of money for fixing our house	"},
{eng : "	Bu kazada maalesef tüm aile öldü.	", tur: "	Whole family was death in this accident.	"},
{eng : "	Ali, 2 gün önce bahçede kötü bir şekilde düştü.	", tur: "	Ali fell off badly in the garden two days ago	"},
{eng : "	Okulun düzenlenmesi için tüm hazırlıklar yapıldı.	", tur: "	All xx was done for xxx fo the school.	"},
{eng : "	Öğretmen sınıfa daha yeni geldi.	", tur: "	The teacher has come to the classroom recently	"},
{eng : "	Şimdiye kadar 3 adet bina inşa edildi.	", tur: "	Three buildings were built by now.	"},
{eng : "	Adam eve gelmeden önce bir otelde kalmış.	", tur: "	The man stayed at a hotel before came the home.	"},
{eng : "	Yarın iki devlet arasındaki anlaşma iptal edilecek.	", tur: "	Agreement between two counties will canceled tomorrow	"},
{eng : "	Kara bulutlar var, yağmur yağacak.	", tur: "	There are black clouds, xxx	"},
{eng : "	Herkes buraya geldiğinde, burası çok tartışmalı olacak.	", tur: "	this place will 	"},
{eng : "	Benim için şarkı söyleyen kadını bir daha göremedim.	", tur: "	I didn't see the woman sings for me.	"},
{eng : "	Ayşe, bir gün Mars’a yolculuk yapacağını söyledi.	", tur: "	Ayşe said that she will go to the mars 	"},
{eng : "	Bir öğretmen olmasına rağmen, öğrencileri nasıl etkilemesi gerektiğini bilmiyor.	", tur: "	She don't know 	"},
{eng : "	İşçilerin yaşına ve cinsiyetine bakılmaksızın, hepsine eşit davranmamız gerekiyor.	", tur: "		"},
{eng : "	Bana söylediğin sözleri annem duyduğunda ne der biliyor musun ?	", tur: "		"},
{eng : "	Seni ilgilendirmeyen konulara dahil olman hiç hoş değil.	", tur: "		"},
{eng : "	Organizasyonun sürecinden ziyade görevlilerin suçunun belirtilmesi gerekiyor.	", tur: "		"},
    
    
    {eng : "	Biz şu an ırak kenarındayız.	", tur: "	We are at the edge of the river now (right now.	", 	seviye: "	1	"},
{eng : "	Akıllı bir adam değildir.	", tur: "	He is not a smartman.	", 	seviye: "	1	"},
{eng : "	Neden hala buradasın.	", tur: "	Why are you still here?	", 	seviye: "	1	"},
{eng : "	Bu yemekler çok lezzetli ve ucuz.	", tur: "	These dishes are very delicious(tasty) and cheap.	", 	seviye: "	1	"},
{eng : "	Aşk insanlar için paha biçilmezdir.	", tur: "	The love is priceless(invaluable, inestimable) for people.	", 	seviye: "	1	"},
{eng : "	Aşk sadece insanlar için paha biçilmez değildir.	", tur: "	The love is not only priceless for people.	", 	seviye: "	1	"},
{eng : "	Aşk sadece insanlar için paha biçilmez değildir. Aynı zamanda hayvanlar içinde değerlidir.	", tur: "	The love is not only priceless for people but also it is valuable for animals.	", 	seviye: "	1	"},
{eng : "	Salı günü eve uğramam.	", tur: "	I don't come home on Tuesday.	", 	seviye: "	2	"},
{eng : "	Bütün işyerleri genellikle gece saat 12'de kapanır.	", tur: "	All work places close at 12 o'clock at night.	", 	seviye: "	2	"},
{eng : "	İnsanlar ellerini yıkamak için sabun kullanır.	", tur: "	The people use the soap to wash their hands.	", 	seviye: "	2	"},
{eng : "	Öğretmeni dinlemek yerine dışarı çıktı.	", tur: "	She went out instead of listening to teacher. (listen to alır)	", 	seviye: "	2	"},
{eng : "	Seni görmeme rağmen bana bakmadın.	", tur: "	Even though I saw you, you didn't look at me. (look at alır)	", 	seviye: "	3	"},
{eng : "	Özellikle düşüncelerine bayıldım.	", tur: "	I especially liked your thoughts.	", 	seviye: "	3	"},
{eng : "	Eve geldiğinde seni bekliyor olacağım.	", tur: "	When you come home, I will be waiting for you. (wait for alır) 	", 	seviye: "	3	"},
{eng : "	Bütün belgeler hazırlandı. Yarın sözleşme imzalanacak.	", tur: "	All documents were prepared. The contract is going to be signed tomorrow.	", 	seviye: "	3	"},
{eng : "	Bisiklet ile giderek en büyük hatayı yaptın.	", tur: "	You made the biggest mistake by going on a bike.	", 	seviye: "	3	"},
{eng : "	Vücudun çok su kaybetti, bu yüzden sürekli hasta oldun.	", tur: "	Your body lost much water, so (so that) you became ill all the time.	", 	seviye: "	3	"},
{eng : "	Geminin bozulan parçası için yeni bir sipariş verildi.	", tur: "	A new one was ordered for the damaged part of the ship.	", 	seviye: "	3	"},
{eng : "	Şu ana kadar fazla hata yapıldığındna dolayı kimse sorumluluk almıyor.	", tur: "	Nobody takes responsibility because more mistakes have been made so far.	", 	seviye: "	3	"},
{eng : "	Tüm çalışanlar odaya girerken, müdür ayakta duruyordu.	", tur: "	While all employees were entering the room, the manager was standing up. 	", 	seviye: "	3	"},
{eng : "	Adamın bankaya girmesiyle çıkması bir oldu. Kimse bir şey anlamadı.	", tur: "	The man scarcely went into the bank, when he came out. Anybody didn't understand anything.	", 	seviye: "	3	"},
{eng : "	Kötü olarak tanımlanan bazı şeyler diğer insanlara göre iyi olabilir.	", tur: "	Some things that (which) are defined badly may be better than the other people.	", 	seviye: "	4	"},
{eng : "	Bir fabrikada tüm süreçlerin başladığı nokta üretim olarak tanımlanır.	", tur: "	The point where all processes start at a factory is defined as production.	", 	seviye: "	4	"},
{eng : "	Bir problemi çözmenin en temel yolu onun kaynağını tahmin etmektir.	", tur: "	The most fundamental way to solve a problem is to forecast the source of it.	", 	seviye: "	4	"},
{eng : "	Sesin düzeyini ayarlayan adamı göre Ayşe bir anda ayağa kalktı.	", tur: "	Ayşe who saw the man that adjusted the level of volume stood up suddenly.	", 	seviye: "	5	"},
{eng : "	Siz hiç insan yiyen timsah gördünüz mü? Ben hayatım boyunca görmedim.	", tur: "	Have you ever seen the crocodile that eats the human? I have not seen in my life.	", 	seviye: "	5	"},
{eng : "	Sinema oyuncuları sahneye gelir gelmez herkes onları alkışlamaya başladı.	", tur: "	As soon as the movie players came on the stage, everyone started to clap.	", 	seviye: "	5	"},
{eng : "	Kız kardeşin iki gün önce İstanbuldaydı.	", tur: "	Your sister was in Istanbul two days ago.	", 	seviye: "	1	"},
	]


for(x of dizi){   
	
	cevir.innerHTML += `
	<div class="scene scene--card" onclick="cardCevir()">
			<div class="card">
				<div class="card__face card__face--front eng">${x["eng"]}	
					<button class="buton">remove</button>
					<button class="buton">star</button>				
				</div>
				<div class="card__face card__face--back tur">${x["tur"]}</div>
			</div>
		</div>`;
		
		
}

function cardCevir(){	
	//console.log(event.target.parentElement);
	event.target.parentElement.classList.toggle('is-flipped');
}





